# ==============================================================================
# Qiskit Settings
# ==============================================================================


title: Qiskit
description: A university quantum algorithms/computation course supplement based on Qiskit

header:
  logo: /logo.svg
  logoWidth: 105
  banner: /banner.jpg

tutor:
  enabled: false

courses:
  revealAll: true
